version: '3.8' # Docker Engine 19.03.0+ - https://docs.docker.com/compose/compose-file/compose-versioning/
services:
  postgresql:
    container_name: # <- set custom container name
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - ${POSTGRES_LISTEN_PORT}:5432
    volumes: 
      - ./volumes/postgresql:/var/lib/postgresql/data
  pgadmin:
    container_name: # <- set custom container name
    expose:
      - 80
    ports:
      - ${PGADMIN_LISTEN_PORT}:80
    image: dpage/pgadmin4:7.7
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
